### ISSUE TITLE
Prelude.read:no parse Error

### ISSUE THREAD

**Issue by antmarge** [stschiff/sequenceTools#10]
I get this error when running pileupCaller:
`pileupCaller: Prelude.read: no parse`
There's no other information other than that line.

Here's the command that I run:
```
 samtools mpileup -R -B --min-BQ 30 --min-MQ 30 --positions pos_file.txt \
            --fasta-ref hg19.fa --bam-list bam_list.txt | sed 's/chr//g' | \
        pileupCaller --sampleNameFile sample_list_file \
                --samplePopName "Pop" \
                --snpFile snp_file.txt \
                -o EigenStrat -e out_prefix
```
pos_file is tab delimited with two columns like this (just the chrom, pos of snp_file):
```
chr1    752566
chr1    776546
```

snp_file is tab delimited with 6 columns in Eigenstrat format:
```
rs3094315       1       0.020130        752566  G       A
rs12124819      1       0.020242        776546  A       G
rs28765502      1       0.022137        832918  T       C
rs7419119       1       0.022518        842013  T       G
```

I've also tried running the command without piping from mpileup to pileupCaller, as well as without changing the chromosome notation in between. Same error.

I'm using sequenceTools version 1.2.2, downloaded with conda

**Comment by stschiff** [comment]
Yeah, sorry about having used functions that through this kind of unhelpful error. You're using a version from July 2018, and a lot has changed since then. I can't exclude that this problem occurs also in the latest version, but I have a hard time now finding out what might cause this in this old version.

Could you please
1) Install the latest version according to the GitHub readme, using `stack install`?
2) If the error persists, try and prepare a reproducible example with a pileup file and a SNP file?

Thank you.

**Comment by antmarge** [comment]
I got the stack install to work on my local computer. The error message says the input is out of order (e.g. chrX comes before chr20 or chr19 comes before chr18). I realized that the pileup output is sometimes out of order even though the snp position file in pileup is sorted 1...22,X,Y. Piping pileup output into sort so that it's 1...22,X,Y and then into pileupCaller seemed to solve the issue. I couldn't get stack install to work on our server, but used the conda version (which gave the ambiguous Parse error) and it worked. So I suspect the parse error was the same as the out of order error.

**Comment by stschiff** [comment]
Brillant. OK then. And I hope we have an updated conda version soon

**Comment by stschiff** [comment]
Just realised that this issue of non-sorted output despite a sorted SNP file might be caused by a non-sorted BAM file. I'm not actually sure how non-sorted bam files are handled by `samtools mpileup` with a SNP list. I would suggest to make sure your bam file is sorted before running `samtools mpileup`. Just a thought.
